# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProdInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eProdInfo.proto\x12\x0bproductInfo\"\x1b\n\x0bInfoRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"N\n\tInfoReply\x12\x10\n\x08res_name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x05\x12\x0f\n\x07\x63ompany\x18\x03 \x01(\t\x12\x0f\n\x07made_in\x18\x04 \x01(\t2L\n\x04Info\x12\x44\n\x0cMultipleInfo\x12\x18.productInfo.InfoRequest\x1a\x16.productInfo.InfoReply(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ProdInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INFOREQUEST._serialized_start=31
  _INFOREQUEST._serialized_end=58
  _INFOREPLY._serialized_start=60
  _INFOREPLY._serialized_end=138
  _INFO._serialized_start=140
  _INFO._serialized_end=216
# @@protoc_insertion_point(module_scope)
